# Apache YAML Features for Git Repositories
# See the documentation at: https://github.com/apache/infrastructure-asfyaml/blob/main/README.md

github:
  description: "Apache Lucene.NET Extensions"
  homepage: https://lucenenet.apache.org/
  labels:
    - lucenenet
    - lucene
    - text
    - search
    - information
    - retrieval
    - analysis
    - index
    - query
    - apache
    - hacktoberfest

  features:
    # Enable wiki for documentation
    wiki: false
    # Enable issues management
    issues: false
    # Enable projects for project management boards
    projects: false
